ARG PYTHON_VERSION=3.8.7
FROM python:${PYTHON_VERSION}-slim-buster

ENV PYTHONUNBUFFERED=1 \
    PYTHONFAULTHANDLER=1 \
    PYTHONHASHSEED=random \
    PIP_DEFAULT_TIMEOUT=100 \
    PIP_DISABLE_PIP_VERSION_CHECK=1 \
    PIP_NO_CACHE_DIR=1 \
    POETRY_VERSION=1.1.15

WORKDIR /app

# copy source code
COPY ./ .


CMD ["bash"]